import { pluginFactory } from './pluginFactory';
import { dispatchPlugin, effectsPlugin } from './plugins';
import { createRedux } from './createRedux';
import { validate } from './utils';
var corePlugins = [dispatchPlugin, effectsPlugin];
/**
 * Rematch class
 *
 * an instance of Rematch generated by "init"
 */

export function Rematch(config) {
    var _this = this;
    this.plugins = [];
    this.pluginFactory = pluginFactory();
    this.config = config;
    for (
        var _i = 0, _a = corePlugins.concat(this.config.plugins);
        _i < _a.length;
        _i++
    ) {
        var plugin = _a[_i];
        this.plugins.push(this.pluginFactory.create(plugin));
    }
    // preStore: middleware, model hooks
    this.forEachPlugin('middleware', function(middleware) {
        _this.config.redux.middlewares.push(middleware);
    });
}
Rematch.prototype = {
    constructor: Rematch,
    forEachPlugin(method, fn) {
        this.plugins.forEach(function(plugin) {
            if (plugin[method]) {
                fn(plugin[method]);
            }
        });
    },
    getModels(models) {
        return Object.keys(models).map(function(name) {
            return Object.assign({ name: name }, models[name]);
        });
    },
    addModel(model) {
        validate([
            [!model, 'model config is required'],
            [typeof model.name !== 'string', 'model "name" [string] is required'],
            [model.state === undefined, 'model "state" is required']
        ]);
        // run plugin model subscriptions
        this.forEachPlugin('onModel', function(onModel) {
            return onModel(model);
        });
    },
    init() {
        var _this = this;
        // collect all models
        this.models = this.getModels(this.config.models);
        this.models.forEach(function(model) {
            this.addModel(model);
        }, this);
        // create a redux store with initialState
        // merge in additional extra reducers
        var redux = createRedux.call(this, {
            redux: this.config.redux,
            models: this.models
        });
        var rematchStore = Object.assign({}, redux.store, {
            // dynamic loading of models with `replaceReducer`
            model: function(model) {
                _this.addModel(model);
                redux.mergeReducers(redux.createModelReducer(model));
                redux.store.replaceReducer(
                    redux.createRootReducer(_this.config.redux.rootReducers)
                );
            }
        });
        this.forEachPlugin('onStoreCreated', function(onStoreCreated) {
            return onStoreCreated(rematchStore);
        });
        rematchStore.dispatch = this.pluginFactory.dispatch;
        return rematchStore;
    }
};
