const hasLengthUnit = {
  border: true,
  borderBottom: true,
  borderLeft: true,
  borderTop: true,
  borderRight: true,
  borderLeftWidth: true,
  borderTopWidth: true,
  borderRightWidth: true,
  borderBottomWidth: true,
  borderWidth: true,
  outlineWidth: true,
  borderImageWidth: true,
  borderBottomLeftRadius: true,
  borderTopLeftRadius: true,
  borderImageOutset: true,
  borderBottomRightRadius: true,
  borderTopRightRadius: true,
  borderRadius: true,
  height: true,
  maxHeight: true,
  maxWidth: true,
  minHeight: true,
  minWidth: true,
  width: true,
  fontSize: true,
  margin: true,
  marginTop: true,
  marginBottom: true,
  marginLeft: true,
  marginRight: true,
  columnCount: true,
  columnGap: true,
  columnWidth: true,
  padding: true,
  paddingLeft: true,
  paddingBottom: true,
  paddingRight: true,
  paddingTop: true,
  bottom: true,
  top: true,
  left: true,
  right: true,
  letterSpacing: true,
  lineHeight: true,
  textIndent: true,
  wordSpacing: true
};

const CSSProperty = {
  hasLengthUnit: hasLengthUnit,
};

module.exports = CSSProperty;